// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUtDCffRoc-Ma2SI5FYBR9bw_nSwVNgn4',
    appId: '1:230871046341:web:54f08ae6cd5d1c983bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    authDomain: 'e-commerce-db515.firebaseapp.com',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
    measurementId: 'G-QHLWRP83DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGD4t2As4mRoxIKsyjWUNNbitkvvW9Aks',
    appId: '1:230871046341:android:b5e2441cb678891e3bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUtDCffRoc-Ma2SI5FYBR9bw_nSwVNgn4',
    appId: '1:230871046341:web:b42745425882feab3bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    authDomain: 'e-commerce-db515.firebaseapp.com',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
    measurementId: 'G-90KS6K0GYS',
  );
}
