name: e_commerce_riverpod
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: 0.14.1
  intl: 0.19.0
  flutter_layout_grid: 2.0.7
  flutter_rating_bar: 4.0.1
  go_router: 14.4.1
  riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  rxdart: 0.28.0
  sembast: 3.7.5
  sembast_web: 2.4.0
  path_provider: 2.1.5
  firebase_core: ^3.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  flutter_lints: 5.0.0
  mocktail: 1.0.4
  build_runner: 2.4.13
  riverpod_generator: 2.6.2
  custom_lint: 0.7.0
  riverpod_lint: 2.6.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
