// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUtDCffRoc-Ma2SI5FYBR9bw_nSwVNgn4',
    appId: '1:230871046341:web:54f08ae6cd5d1c983bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    authDomain: 'e-commerce-db515.firebaseapp.com',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
    measurementId: 'G-QHLWRP83DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGD4t2As4mRoxIKsyjWUNNbitkvvW9Aks',
    appId: '1:230871046341:android:cdb419572b413dc83bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3mH40CPF8cWNXN58BZPgHfrIxqzP7ZmA',
    appId: '1:230871046341:ios:08ca3f363f2cd11a3bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3mH40CPF8cWNXN58BZPgHfrIxqzP7ZmA',
    appId: '1:230871046341:ios:08ca3f363f2cd11a3bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUtDCffRoc-Ma2SI5FYBR9bw_nSwVNgn4',
    appId: '1:230871046341:web:960b174f364680ea3bf8ac',
    messagingSenderId: '230871046341',
    projectId: 'e-commerce-db515',
    authDomain: 'e-commerce-db515.firebaseapp.com',
    storageBucket: 'e-commerce-db515.firebasestorage.app',
    measurementId: 'G-MM0HJX1CD4',
  );

}